### ISSUE TITLE
 write R code using aws.s3 🐙 

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#114]
write R code, following https://blog.djnavarro.net/posts/2022-03-17_using-aws-s3-in-r

**Comment by jules32** [comment]
Our AWS credentials seem to make the aws.s3 code fail. Some recent notes to Luis: 

> Hi! I've been reading more about aws.s3 (thinking if no one else is talking about this I'm the one doing something wrong, not the package?). The [aws.s3](https://github.com/cloudyr/aws.s3) docs lead me to [aws.signature](https://github.com/cloudyr/aws.signature) and there are other options that might be relevant, potentially 3. about EC2 instances and a third package [aws.ec2metadata](https://github.com/cloudyr/aws.ec2metadata) (all by the same group of people, some of whom made rocker!). But I'm over my head - could you have a look and see if any of these are worth me pursuing?

**Comment by cassienickles** [comment]
Already done
