### ISSUE TITLE
importing notebooks from external repos

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#168]
Writing up notes from our Feb 2 Hackday with @betolink @Alex-Lewandowski @battistowx

## Progress
Following [workflow instructions written in the cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/workflow.html#including-remote-notebooks), we:  

- created the `import-breakout` branch https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/tree/import-breakout
- imported openSARLab test file (see code just below)
- [Quarto error in the GitHub Action](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/actions/runs/4077224575), troubleshooted in hub and local RStudio. Due to `---`, diagnosed and  fixed by hand

```
title: "OpenSARLab example"
preamble: "test"
source: "https://github.com/ASFOpenSARlab/opensarlab-notebooks"
url: "https://raw.githubusercontent.com/ASFOpenSARlab/opensarlab-notebooks/master/SAR_Training/English/Master/Change_Detection_Amplitude_Time_Series_Example.ipynb"
target: "opensarlab-test.ipynb"
process: true
```

## Next Steps

1. Media urls  (relative urls don't import over)
1. Julie test quarto error in Staging hub with most recent version of Quarto
1. Move all 2021 Cloud Hackathon tutorials over

**Comment by jules32** [comment]
I've confirmed we still get the error in the staging hub, I'll follow up with the Quarto team

**Comment by jules32** [comment]
I will import the 2021 Cloud Hackathon Tutorials before our Hackday on Thursday

**Comment by jules32** [comment]
Done, awaiting review and merge: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/176

**Comment by stefaniebutland** [comment]
can this be closed @jules32 ?

**Comment by jules32** [comment]
yes, thanks!
