### ISSUE TITLE
Add Pull Request Review to Contributing section

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#173]
This is already scaffolded from Amy Steiker's [coworking notes on Feb 14](https://docs.google.com/document/d/1fzT-iSFlWZLS38eoPmFseljyMKDQIAc-24qH6QpnRCc/edit#), and there is a video recording to watch too!

**Comment by stefaniebutland** [comment]
PR https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/224

**Comment by stefaniebutland** [comment]
merged https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/workflow.html#review-a-pull-request
