### ISSUE TITLE
update importer function to include .md files

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#174]
https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/_import/quarto_import.py

To tackle at this week's Cookbook Hackday

**Comment by jules32** [comment]
When you do this, could you please also: 

- [ ] import https://github.com/NASA-Openscapes/2021-Cloud-Hackathon/blob/main/tutorials/00_Setup.md

**Comment by cassienickles** [comment]
If importing any file other than .ipynb files, requires "process: false" in the asset .json file for the specific file.

This has been merged in PR #179
