### ISSUE TITLE
Update and add Cloud OPeNDAP tutorials

### ISSUE THREAD

**Issue by battistowx** [NASA-Openscapes/earthdata-cloud-cookbook#177]
Compile various Cloud OPeNDAP tutorials and consolidate/refactor existing how-tos in the Cookbook. These could be inside the "Working with cloud data on your local machine" tab, and may apply simple examples of accessing Daymet and PO.DAAC granules.

Features included in how-tos may include:

- Simple comparison of DAP2/DAP4 constraint expressions
- "Streaming" granules with Xarray
- wget/curl downloading and subsetting
- ncdump downloading/metadata viewing, including nccopy

**Comment by jules32** [comment]
@battistowx's notebook: `177-opendap-tutorials` branch

https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/177-opendap-tutorials/how-tos/working-with-data-in-cloud/Earthdata_Cloud__Data_Access_OPeNDAP_Example.ipynb
