### ISSUE TITLE
setup migration from Cloud Hackathon part 2: PAT tokens

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#201]
Review this whole page and bring into Cookbook, but particularly the PAT details from Makhan: 

https://nasa-openscapes.github.io/2021-Cloud-Hackathon/tutorials/00_Setup.html#step-5.1.-configure-git-git-config

`git config --global credential.helper store`

**Comment by cassienickles** [comment]
PATs no longer needed for 2i2c workflows
