### ISSUE TITLE
Changes to contributing/setup.qmd don't appear live

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/earthdata-cloud-cookbook#225]
I'm stumped.

Changes I made in merged PR https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/220 to [`contributing/setup.qmd`](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/contributing/setup.qmd) are in the source file but are not live in the [Cookbook: Contributing: Setup](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/setup.html).

- Example: "JupyterLab" in source appears "Jupyter Lab" in book

Changes I made in the same PR to [`contributing/workflow.qmd`](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/contributing/workflow.qmd) do appear live.

- Example: added Cookbook Editing heading

**Comment by stefaniebutland** [comment]
try to make these changes in the Hub and see what happens

**Comment by jules32** [comment]
@stefaniebutland this is likely due to the code, please change to this notation to have the code not execute and we can update other notebooks with this notation too.  

https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/228#issuecomment-1664652612

**Comment by stefaniebutland** [comment]
woohoo! fixed by setting code not to run with e.g.
```
```python
```
