### ISSUE TITLE
Link broken on home page

### ISSUE THREAD

**Issue by BriannaLind** [NASA-Openscapes/earthdata-cloud-cookbook#226]
Link called "How We Work" under the subheading NASA's cloud migration is broken.  Broken link is highlighted in yellow in image below.

![image](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/assets/104585874/8ed5f7f5-c13c-49d3-836b-1269d24b8fc7)

**Comment by stefaniebutland** [comment]
Can't find a working link.
- vimeo video link broken here https://2020.fedgeo.us/
- nothing here: https://vimeo.com/showcase/7302594 

I'll ask in Slack for alternative
