### ISSUE TITLE
check & document rendering computational code: `{.bash}` v `{bash}` syntax

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#228]
Carlos S from the Quarto team identified that the `{bash}` syntax will try to execute, despite the yml (see my original question below). Go through for render errors and fix; document this in the contributing section

> We have a [small .qmd with python and R cells](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/how-tos/find-data/programmatic.qmd#L3-L4) that we execute in our JupyterHub with a base image. In the Python base image, we don’t have R installed, and despite having `execute: eval: false` in the .qmd’s yaml, we get an execution error.

**Comment by jules32** [comment]
Update from Christophe: use `{.python}` rather than `.python`. - this made the rendered format as expected with the copy button.

as in the later case will identify the class as being `.python`  and not `python` . The latter is equivalent to
```{..python}```

You can also use

```python```
without `.`  as we document https://quarto.org/docs/authoring/markdown-basics.html#source-code
The `.` before the name if for the class syntax in curly braces syntax. Like with div and spans

**Comment by jules32** [comment]
Code chunks are executed if they are within curly brackets like `{python}`

There are 2 ways for computational code to be ignored: 

```
```python
```

```
```{.python}
```

There are merits for each - `python` is cleaner and follows the rules
- Brackets = computation
- No brackets = static code
(Thus no dot notation)

but `{.python}` has the consistency of the `{ }` notation.

**Comment by jules32** [comment]
Let's go with 

``` 
```python
```

which follows the rules

- Brackets = computation
- No brackets = static code

**Comment by stefaniebutland** [comment]
We're addressing this in #234
