### ISSUE TITLE
Add section about computing cost

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#229]
Share slides we have about cost so far from AWS, including 

We also learned about `[hub url]/metrics` (https://openscapes.2i2c.cloud/hub/api/metrics) from [Yuvi’s awesome blog post](https://blog.jupyter.org/accurately-counting-daily-weekly-monthly-active-users-on-jupyterhub-6fbec6c6ce2f). I search for `active_users` and see this today: 

```
# HELP jupyterhub_total_users total number of users
# TYPE jupyterhub_total_users gauge
jupyterhub_total_users 813.0
# HELP jupyterhub_active_users number of users who were active in the given time period
# TYPE jupyterhub_active_users gauge
jupyterhub_active_users{period="24h"} 20.0
jupyterhub_active_users{period="7d"} 33.0
jupyterhub_active_users{period="30d"} 49.0
```

**Comment by alexishunzinger** [comment]
We can also include examples from NSIDC and Coiled. 

- [AWS Cost Explorer Tips and Tricks](https://blog.coiled.io/blog/aws-cost-explorer-tips.html)

- [Processing Terabyte-Scale NASA Cloud Datasets with Coiled](https://openscapes.org/blog/2023-11-07-coiled-openscapes/)

**Comment by itcarroll** [comment]
Continue discussion in #349.
