### ISSUE TITLE
6. Update Quarto executable syntax throughout .qmds and document

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/earthdata-cloud-cookbook#234]
About: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/issues/228#issuecomment-1664652612

- [x] Stef do setup.qmd update first
    - PR #240 
- [x] Make checklist of all `.qmds` we see in the yaml (done Aug 4, 2023)
- [ ] Stef and Julie update them in one branch in one coworking session
- [ ] Look for code chunks in `.qmd` files. Code chunks in RStudio will be grey; could control-F for ```
- [ ] Document this

**Comment by stefaniebutland** [comment]
Checklist of `.qmd` files in [`earthdata-cloud-cookbook/_quarto.yml`](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/tree/main/_quarto.yml) as of Aug 4, 2023

- [ ] index.qmd
- [ ] when-to-cloud.qmd
- [ ] our-cookbook.qmd
- [ ] cheatsheets.qmd      
- [ ] environment-setup/index.qmd
- [ ] how-tos/index.qmd
- [ ] how-tos/find-data/index.md
- [ ] how-tos/find-data/earthdata_search.md
- [ ] how-tos/find-data/programmatic.qmd                
- [ ] how-tos/access_data.qmd 
- [ ] how-tos/if-im-in-the-cloud.qmd
- [ ] how-tos/if-im-local.qmd
- [ ] how-tos/read_data.qmd
- [ ] how-tos/subset.qmd
- [ ] how-tos/reformat.qmd
- [ ] how-tos/reproject_regrid.qmd
- [ ] how-tos/aggregate.qmd
- [ ] how-tos/plot.qmd
- [ ] how-tos/use_apis.qmd
- [ ] how-tos/tech-setup.qmd
- [ ] how-tos/how_to_guide_parking_lot.md
- [ ] tutorials/index.qmd
- [ ] workshops/setup.md
- [ ] in-development/index.qmd
- [ ] examples/index.qmd
- [ ] in-development/matlab.qmd
- [ ] in-development/CMR-STAC-Search.Rmd
- [ ] in-development/earthdata-python-r-handoff.qmd  
- [ ] contributing/index.qmd
- [ ] contributing/setup.qmd
- [ ] contributing/workflow.qmd
- [ ] contributing/quarto-website-tutorial.md
- [ ] contributing/troubleshooting.md
- [ ] contributing/onboarding.qmd
- [ ] appendix/index.md
- [ ] appendix/authentication.qmd

**Comment by stefaniebutland** [comment]
Set ````{.python}` or ````{.bash} ` as ````python` in _almost all_ of these `qmd` files.

From Julie:
> I think that will be true for 80-90% of the .qmds, there may be a few that are more complex. If you have questions about any of them will you skip, but otherwise I think you can do most of them! I think Amy and Andy are the ones who have made .qmds and most other folks make .ipynbs

**Comment by stefaniebutland** [comment]
Julie will help with in-development ones. Stef do the others.

**Comment by stefaniebutland** [comment]
Files not appearing in `_quarto.yml`

- [ ] contributing/community.md
- [ ] contributing/environment.qmd

**Comment by stefaniebutland** [comment]
working in draft PR: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/244

**Comment by jules32** [comment]
For these files in the checklist above, let's ask @cassienickles @ScienceCat18 and others on Aug 29 during coworking. I'm not sure this is the way Mentors are teaching these topics currently. 
https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/tree/main/how-tos/working-with-data-in-cloud

**Comment by stefaniebutland** [comment]
@ScienceCat18 says most of these have been superseeded by Earthaccess now

**Comment by jules32** [comment]
Found a few more that I fixed to enable the Cookbook to build, following Coworking today
