### ISSUE TITLE
7. Revisit chapter pages - redundant table of contents

### ISSUE THREAD

**Issue by stefaniebutland** [NASA-Openscapes/earthdata-cloud-cookbook#236]
Example see [Tutorials page](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/).

Be opinionated - chapter page should have short paragraph for what chapter includes and say "look at the navbar to see what’s here."

Why? Adding every tutorial to a list on the Tutorials page is an extra step that gives redundant info, people will not think to add them so they'll be less discoverable than if they only appeared in nav bar.

What other chapter pages need this consistent paragraph?

- [ ] make the change
- [ ] document the change

**Comment by stefaniebutland** [comment]
In `_quarto.yml`, should we omit `href: how-tos/access_data.qmd` which is a sort of TOC page? There is not an analogous page for `- section: "find data"` 

```
          - section: "access data" 
             href: how-tos/access_data.qmd   
```

**Comment by stefaniebutland** [comment]
To consider: note, for example, the brief text under each Tutorial heading says what you'll find in that tutorial and this can't be conveyed in nav bar headings.

**Comment by jules32** [comment]
Closing; moving forward we'll have TOC's where they are needed
