### ISSUE TITLE
R How-To link is throwing a 404 error

### ISSUE THREAD

**Issue by asteiker** [NASA-Openscapes/earthdata-cloud-cookbook#258]
This may just be an issue with our TOC? From the navigation, if I click on How do I... -> access data in cloud -> with R I get a 404: https://nasa-openscapes.github.io/earthdata-cloud-cookbook/how-tos/access-data/access-cloud-r.qmd

**Comment by erinmr** [comment]
It looks like the access data in R was deleted in [this revision](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/commit/00c2c85e1a74da327c714e597974942eb47eef76#diff-2c985ea40c39e112ef133129a388421b943f9d47b522a1619d7c4146b25ccb51)

**Comment by jules32** [comment]
Good find @asteiker I will fix and report back by tomorrow!

**Comment by jules32** [comment]
So it looks like we deleted the [access-cloud-r.qmd](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/how-tos/access-data/access-cloud-r.qmd) file until we had R code for access; in its current form this .qmd said only "coming soon" and we decided it was better to add it only when we had code. Being able to select this from the left nav bar is my error – I should have removed it.

<img width="176" alt="image" src="https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/assets/5891909/74d3bcbc-c1b2-4ce0-a097-653f2b3694b2">


I know @BriannaLind and Carl are working on another way to access; we can add that when it's ready. Other options from @amfriesz ([HLS_tutorial.rmd](https://git.earthdata.nasa.gov/projects/LPDUR/repos/hls_tutorial_r/browse/Scripts/HLS_Tutorial.Rmd)) and @rupesh2 ([gedi_l4a_direct_s3_access_r.ipynb](https://github.com/rupesh2/gedil2a_l4a/blob/main/gedi_l4a_direct_s3_access_r.ipynb)). In the meantime, I can remove the R code option from the left navbar.

**Comment by jules32** [comment]
Carl Boettiger's updates are on CRAN (R's official distribution/install)! We'll be able to add this to the Cookbook now; I can help lead and do before AGU.

Update from Carl Boettiger here: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/discussions/247#discussioncomment-7601761
