### ISSUE TITLE
Update Cloud Environment Setup - policies & usage costs 

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#270]
## Idea to add subsections to Cloud Environmental Setup: 
https://nasa-openscapes.github.io/earthdata-cloud-cookbook/environment-setup/. 

To include/consider: 

- Page for costs, based on examples with screenshots 
- Page for 2i2c, corn
- Page for Coiled

Resources to include: 

- https://github.com/NASA-Openscapes/2i2cAccessPolicies
- [How to Add Folks to 2i2c GitHub Teams](https://docs.google.com/document/d/1Ql-JrJUZlXQWsSTpQKgnMDZ_wBFGst2425KvkY-NlYM/edit?pli=1) - evolving, maybe link as published/read-only google doc?

**Comment by alexishunzinger** [comment]
See #284 where Amy is looking to beef up the Environment Setup section with material from the Cloud Playground's Offboarding section

**Comment by cassienickles** [comment]
Duplicate to #349
