### ISSUE TITLE
Add AGU intro slides and recording by Michele

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#274]
Currently here: https://drive.google.com/drive/folders/1F2o5sP-efoDW_u3-ccQd8thLahO0S2Qr. 

- [x] add to youtube (@stefaniebutland)
- [ ] link from https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/setup.html#access-jupyterhub 
- [ ] other places to link?

**Comment by stefaniebutland** [comment]
video on YouTube https://youtu.be/E5Dpeap16hU in new [NASA Openscapes playlist](https://www.youtube.com/playlist?list=PLVVMU2rjWU7fP-iPS61EqxJCHf0I4WLTf)

**Comment by jules32** [comment]
Awesome, thank you Stef!
