### ISSUE TITLE
Add page: How to Add Folks to 2i2c GitHub Teams

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#275]
Create a Cookbook page for the google doc [How to Add Folks to 2i2c GitHub Teams](https://docs.google.com/document/d/1Ql-JrJUZlXQWsSTpQKgnMDZ_wBFGst2425KvkY-NlYM/edit?pli=1) that @erinmr created with our process. This will be part of the new "workshop prep, setup, and hosting" section that @jules32 can help coordinate with the Mentors.

As a first step, @stefaniebutland, could you please copy this document to a .qmd and make a PR? A few notes: 
- [x] create a `leading-workshops` folder to put this qmd in; we may rename later
- [x] create an `images` folder with screenshots - might have to review the process if need higher image quality than from google doc
- [x] format with markdown headers
- [x] make any improvements to text for clarity

**Comment by stefaniebutland** [comment]
working in this [draft PR](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/276)

**Comment by stefaniebutland** [comment]
PR ready for review @jules32. 
I did not include the notes with feedback on specific workshops. Those still in the google doc

**Comment by stefaniebutland** [comment]
> might have to review the process if need higher image quality than from google doc

Screenshots worked well this way: Paste gdoc content into .qmd visual mode. For each image, right-click > save image as ....

**Comment by stefaniebutland** [comment]
merged PR. [Live Cookbook page](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/leading-workshops/add-folks-to-2i2c-github-teams.html)
