### ISSUE TITLE
New contributing page: calendar-project-management.qmd

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#279]
Hi @stefaniebutland can you please start a new contributing page like we talked about, with what you would Slack/say to someone to onboard them. It can be rough, but having it by Tuesday hacktime with Bri would be super so we can iterate. 

(call it `calendar-project-management.qmd` for now) in the contributing folder. Include the starting description of https://github.com/orgs/NASA-Openscapes/projects/7: 

- that it exists, and pulls from several repos: (list/link them and that they correspond to 
- how_we_work: use this as a default for repos in other GH orgs (like nsidc/earthaccess )
- Workshop planning: Calendaring & planning
- Cloud infrastructure: 
  - MATLAB
  - 2i2c access policy & fledging - Julie to coordinate with Yuvi & James (2i2c) 
Cookbook

**Comment by stefaniebutland** [comment]
PR: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/280

**Comment by jules32** [comment]
Closing this since PR was merged
