### ISSUE TITLE
As an ICESat-2 user, I want to know how to access ICESat-2 data from their s3 locations

### ISSUE THREAD

**Issue by asteiker** [NASA-Openscapes/earthdata-cloud-cookbook#28]
Acceptance criteria:

- Chapter published under Cookbook Access section (https://nasa-openscapes.github.io/earthdata-cloud-cookbook/access/ ) 
- Jupyter notebook provides basic steps to:
- 1. Access a list of S3 URLs
- 2. Access data from CMR-STAC catalog
- (TBD) libraries are demonstrated:
- pystac?
- intake?
- boto3?
- others?
- Previous search chapter(s) referenced that demonstrate how to log into EDL, search for ICESat-2 data and retrieve a list of S3 links, and how to locate CMR STAC catalogs

**Comment by jules32** [comment]
@asteiker could you review this and close if it's no longer relevant for our current direction? Thank you!

**Comment by asteiker** [comment]
@jules32 Thanks for the ping! I love seeing how much we've evolved and grown in ~1.5 years (so many question marks back then)! Yes, we can close this out. The steps to discover and access data in s3 from multiple files is in our cookbook already (with earthaccess updates in progress).
