### ISSUE TITLE
Populate When To Cloud section

### ISSUE THREAD

**Issue by alexishunzinger** [NASA-Openscapes/earthdata-cloud-cookbook#293]
Currently the When To Cloud section is in the notebook, but the content is in brainstormed, bulleted form.

We will flesh these bullets out to have a more presentable draft of "When To Cloud" guidance for users.

https://nasa-openscapes.github.io/earthdata-cloud-cookbook/when-to-cloud.html

**Comment by alexishunzinger** [comment]
- [ ] Connect to examples of how the cloud was used and also "when NOT to cloud"
- [ ] Move cloud paradigm diagram from Welcome to When To Cloud, and bring that description along with

**Comment by alexishunzinger** [comment]
- [ ] When To Cloud, When Not To Cloud, How To Cloud

**Comment by betolink** [comment]
Asked for examples in the Pangeo forum https://discourse.pangeo.io/t/cloud-use-cases/4007
