### ISSUE TITLE
Running quarto from source doesn't  work on other (ubuntu, RHEL) versions of linux: Use Docker to install

### ISSUE THREAD

**Issue by muthukumaranR** [NASA-Openscapes/earthdata-cloud-cookbook#30]
#### Description 
Running quarto from source doesn't  work on other (ubuntu, RHEL) versions of Linux.
#### To Reproduce
1. be in ubuntu/RHEL version of linux
2. run quarto as indicated in `https://quarto.org/docs/getting-started/installation.html`
#### Tasks
- [x] Install quarto using docker
-  [x] test the cookbook within docker container

**Comment by jules32** [comment]
Hi @muthukumaranR, do you have the latest version of the Quarto CLI installed: https://github.com/quarto-dev/quarto-cli/releases/latest? 

The latest release was yesterday

**Comment by muthukumaranR** [comment]
Here's an example Dockerfile
```
FROM debian:latest
RUN apt-get -y update
RUN apt-get -y install git
RUN apt-get -y install wget
RUN apt-get -y install unzip
RUN apt-get -y install python3


FROM python:3

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir jupyter

RUN git clone https://github.com/quarto-dev/quarto-cli
RUN cd quarto-cli
RUN ./configure-linux.sh
RUN cd ..
RUN quarto check install
RUN git clone https://github.com/NASA-Openscapes/earthdata-cloud-cookbook
```

once Docker is installed,  run  `docker build -t cookbook-image .` to build the image

**Comment by muthukumaranR** [comment]
@jules32 I think the issue will still be there if Linux version is not Debian, as it looks like the `configure-linux.sh` file hasn't been changed, but I'll try this and let you know.

**Comment by jjallaire** [comment]
What specific errors are you seeing? We _should_ work on Ubuntu at the least (that's what we develop and test on).

cc @dragonstyle

**Comment by muthukumaranR** [comment]
Hi @jules32 and @jjallaire, I can confirm the latest quarto branch works on the latest ubuntu and centos images. Thanks a lot for the clarification. closing the issue

Just a side note:  I've encountered Glibc issue installing deno on RHEL 7 (I think it is because of deno requiring updated C++ versions which is not available in RHEL 7) which made me resort to docker installation (which works well)
