### ISSUE TITLE
Cloud Clinic: AttributeError opening results

### ISSUE THREAD

**Issue by graymckenna96** [NASA-Openscapes/earthdata-cloud-cookbook#305]
Hi there! I am pretty new to python and I'm trying to follow along with the Earthdata Cloud Clinic and am running into an error in the "Access data" step:
![Screenshot 2024-02-09 135848](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/assets/148900123/9f282474-924e-4165-8269-9613e13f94fe)

I am working in a py script in VS code, and I have all the packages installed. My script is just copied and pasted from the [clinic ](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/examples/Earthdata-cloud-clinic.html)page. Everything seems to work up to this point and I can see in the terminal the dataset is loading into the results variable since my pprint() returns all the same info in the example. What's causing this? 

Thanks!

**Comment by graymckenna96** [comment]
Nevermind, realized my login() wasnt working which i hadn't realized since search() worked. carrying on now.

**Comment by jules32** [comment]
Ah great, thanks for following up @graymckenna96 !
