### ISSUE TITLE
Link to IceSat2 tutorial gives a "404 error"

### ISSUE THREAD

**Issue by carlnorlen** [NASA-Openscapes/earthdata-cloud-cookbook#327]
When I try to navigate to the IceSat2 tutorial on the Cloud Cookbook website I get a "404 error". Has that tutorial been removed or does the link need to be updated?

**Comment by andypbarrett** [comment]
I checked `https://nasa-openscapes.github.io/earthdata-cloud-cookbook/external/IS2_cloud_Landsat_integration.ipynb` and the notebook is no longer in the `external` path.  I'm not seeing it anywhere else.  Did it get removed?

**Comment by asteiker** [comment]
Duplicate: #357
