### ISSUE TITLE
Add earthaccess more prominently to Cookbook homepage

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#332]
Add earthaccess more prominently to Cookbook, maybe under [Welcome header](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/#welcome), it could be simple like on https://nasa-openscapes.github.io/ homepage, maybe saying 

```
"earthaccess is a python library to access NASA earthdata locally or in the cloud. Learn more here, see this tech spotlight (blog link), this earthdata blogpost, and these tutorials"

Looking for R and MATLAB libaries? see earthdatalogin's page and tutorials (in cookbook), and MATLAB's tutorials (link in cookbook)
```

 What do you all Mentors think? There is a blog coming out about earthdatalogin and this will be great to have!

**Comment by stefaniebutland** [comment]
We'll add this to Cookbook and get Mentors' feedback in Coworking June 6
