### ISSUE TITLE
Create a .ipynb virtual environment

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#47]
Hi @betolink, 

This might go along with #46 with @asteiker but would you be able to add a virtual environment to our Cookbook like we've talked about with J.J. (https://github.com/quarto-dev/quarto-cli/issues/41)?

It would be great if you could push that as a PR so we can learn from/with you about how others can go about it too! If you are able to write up instructions for us too in [ earthdata-cloud-cookbook/contributing/workflow.md ](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/contributing/workflow.md) that would be awesome. 

Let me know if you want to meet/screenshare about it too!

**Comment by betolink** [comment]
I'm working on a virtual environment for the NSIDC chapter but we'll need the ones for the other DAACs. I also opened this issue https://github.com/2i2c-org/pilot/issues/81 on 2i2c to make this multi environment available on the hub.
