### ISSUE TITLE
Data Access COF example with ECCO data

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#48]
Hi @ScienceCat18, we’re tagging you to work on this so we can start tackling and closing issues as we develop the Cookbook.

Could you please add a new chapter for ECCO in the same style as [ earthdata-cloud-cookbook/access/podaac-ecco-data_access-cloud_direct_access_s3.ipynb ](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/access/podaac-ecco-data_access-cloud_direct_access_s3.ipynb). This will mean copying your existing `.ipynb` (or equivalent) to our repo and adding it to our [`_quarto.yml` after line 50](https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/blob/main/_quarto.yml#L50). This will mean turning an existing page into a section, which I can talk through/screenshare with you if you'd like.

It would be great if you can start pushing updates to GitHub as you develop it so we can all see progress and get/give feedback. And if there is someone else who you think would be a better fit for this issue or from whom you'd like feedback, please respond here and tag them!

You can refer to our [outline google doc](https://docs.google.com/document/d/12uEPP_w4M4SMrLkcVzUwX7htWtTzlS5a3ahJnK7fSAs/edit) for some more planning context, as well as notes for our [contributing workflow](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/workflow.html) for how to do work with GitHub branches and Quarto. Totally happy to talk through more and screenshare at a co-working session (or Slack us to set another time)!

**Comment by ScienceCat18** [comment]
@jules32 should I still work on this, or have things evolved since this was opened? I know we've been talking about connecting original notebooks into Cookbook, over bringing in a copy? Should I look into how to do that instead? I think Luis was working on that process, is there a readme/workflow I can follow?

**Comment by ScienceCat18** [comment]
@jules32 I think I am up to speed a bit now. I am following these instructions on how to pull in a remote notebook https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/workflow.html under "Including Remote Notebooks" assuming it's up to date. I'll try doing that for this COF example with ECCO data, and place it under Data Access for now (we may be restructuring order anyway following the Divio documentation best practices). Once I do it locally I'll do a PR.

**Comment by jules32** [comment]
Sounds great, thanks Catalina

**Comment by jules32** [comment]
Nice @ScienceCat18, I've merged your PR (https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/pull/78) so I'll close this issue here. 🥳
