### ISSUE TITLE
Early chapter to fish data out of HDF5 to make it look the same

### ISSUE THREAD

**Issue by erinmr** [NASA-Openscapes/earthdata-cloud-cookbook#58]

**Comment by erinmr** [comment]
Cloud optimized and want to talk to scientist about their needs.

**Comment by jules32** [comment]
Relevant article:https://medium.com/pangeo/cloud-performant-netcdf4-hdf5-with-zarr-fsspec-and-intake-3d3a3e7cb935

**Comment by cassienickles** [comment]
This has been addressed elsewhere
