### ISSUE TITLE
Include text on installing quarto without admin password

### ISSUE THREAD

**Issue by alexishunzinger** [NASA-Openscapes/earthdata-cloud-cookbook#69]
Request by @jules32 to @alexishunzinger to add text about the new feature in the quarto install process.

From Charles at RStudio:
"Ok I've got a build that I would love for you all to try out. This build should support either machine or per user installation:
https://github.com/quarto-dev/quarto-cli/releases/tag/v0.1.367

Note that you can select whether the installation or per machine or per user using the 'install location' option. The per user installation shouldn't require any administrative privilege and so hopefully will work well for Alexis/Chandana.

Let me know if you have feedback or need me to jump on to troubleshoot issues!"

From @jules32 on Slack:
Charles from Quarto updated the admin install requirements and would love you to test: could you see if you could install without docker? 
Would you be able to add a few sentences of how you did it to https://nasa-openscapes.github.io/earthdata-cloud-cookbook/contributing/setup.html#install-quarto?

**Comment by jules32** [comment]
PR merged; closing this issue
