### ISSUE TITLE
Import more PODAAC notebooks from remote

### ISSUE THREAD

**Issue by jules32** [NASA-Openscapes/earthdata-cloud-cookbook#76]
@ScienceCat18 will import a couple more notebooks via "remote linking" in the cookbook in temporary branches (and do PRs)

**Comment by cassienickles** [comment]
How do we want to integrate multiple cookbook sources? Better forum for discussion

**Comment by itcarroll** [comment]
Here's the discussion: https://github.com/NASA-Openscapes/earthdata-cloud-cookbook/discussions/356
